# docker-compose.yml
version: "3.9"
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.7
    ports: ["9092:9092"]
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on: [zookeeper]

  consumer:
    image: kafka-consumer:test
    env_file:
      - kafka-consumer/.env.shared
      # - kafka-consumer/.env.secret        # ← CHANGED (commented out – not needed for PLAINTEXT)
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092    # already overrides the host
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT    # ← CHANGED (disable SASL)
      KAFKA_SASL_MECHANISM: ""              # ← CHANGED (empty so client won’t try SCRAM)
    depends_on: [kafka]
