apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  selector:
    app: kafka-consumer
  ports:
  - port: 8080   # not actually needed unless consumer exposes HTTP
    targetPort: 8080
